name: Rest API Tests using Rest Assured with TestNG
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
      
    - name: Test Execution
      run: mvn clean test

    - name: Build with Maven
      run: mvn -B package --file pom.xml
        
    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
          name: TestNG Report                 # Name of the folder
          path: C:/Users/udeme/Downloads/web-automation-master/Bkups/RestAssured/target      # Path to test results
